name: Docker

on:
  push:
    tags:
      - '[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: olegtarasov/get-tag@v2
        id: tagName

      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: poppen/asterisk-fax
          tags: latest,${{ steps.tagName.outputs.tag }}
        env:
          DOCKER_BUILDKIT: 1
